/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_jni_testjni */

#ifndef _Included_com_example_test_jni_testjni
#define _Included_com_example_test_jni_testjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_test_jni_testjni
 * Method:    pass
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_test_1jni_testjni_pass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
