/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_crackme_RjJNI */

#ifndef _Included_com_example_crackme_RjJNI
#define _Included_com_example_crackme_RjJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_crackme_RjJNI
 * Method:    pass
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_crackme_RjJNI_pass(JNIEnv * env,jclass pass){
return (*env)->NewStringUTF(env,"yiming-yrj");
}

#ifdef __cplusplus
}
#endif
#endif
